### PR TITLE
fix: fix Connection.getMetaData().getColumns returns wrong/fixed values for column data type details (#733)

### LINKED ISSUE #733: Connection.getMetaData().getColumns returns wrong/fixed values for column data type details
Using the `ResultSet` returned by `Connection.getMetaData().getColumns()` returns wrong values for the size of the column.

Especially these values are wrong:
- `COLUMN_SIZE` (fixed `10`)
- `DECIMAL_DIGITS` (fixed `2000000000`)

The `DATA_TYPE` is correct, but the client is unable to detect the size of the column or the precision of floating point values.

_Example:_
I have a table with this column: `ORIENTATION REAL(6,3)`

This is what I get:

- `COLUMN_NAME`=`"ORIENTATION"` (correct)
- `TYPE_NAME`=`"REAL(6,3)"` (correct)
- `DATA_TYPE`=`6` (correct, is `java.sql.Types.FLOAT`)
- `COLUMN_SIZE`=`2000000000` (wrong, should be `9`?, `6+3`)
- `DECIMAL_DIGITS`=`10` (wrong, should be `3`)

The cause for this can be found [here](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java#L920) and [here](https://github.com/xerial/sqlite-jdbc/blob/master/src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java#L922).

I just did not found a simple fix, so I add this issue instead of a pull request 😉

### PR DESCRIPTION
**Pull request by sebasbaumh**
* provide valid COLUMN_SIZE and DECIMAL_DIGITS values for columns queried using
 Connection.getMetaData().getColumns(java.lang.String, java.lang.String, java.lang.String, java.lang.String)
* add/adjust unit tests to test this change

Fixes #733

### CODE REVIEW

File: src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java [hunk 1]
```diff
@@ -1011,14 +1015,62 @@ public ResultSet getColumns(String c, String s, String tblNamePattern, String co
...
+                                        // no decimals
+                                        iDecimalDigits = 0;
+                                        // columns size equals dimension
+                                        iColumnSize = iInteger;
+                                    }
+                                } catch (NumberFormatException ex) {
+                                    // just ignore invalid dimension formats here
+                                }
+                            }
+                        }
```
Comment (gotson) [inline src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java:1073]: What do you think of using regex instead of `indexOf`/`substring` ?

Would need to define this somewhere:
```java
protected static final Pattern COLUMN_LENGTH = Pattern.compile(".*\\((?<integer>[0-9]+)(,(?<decimal>[0-9]+))?\\)");
```

Then we can replace this whole block:

```suggestion
                        Matcher matcher = COLUMN_LENGTH.matcher(colType);
                        if (matcher.matches()) {
                            try {
                                iDecimalDigits = matcher.group("decimal") == null ? 0 : Integer.parseUnsignedInt(matcher.group("decimal"));
                                iColumnSize = Integer.parseUnsignedInt(matcher.group("integer")) + iDecimalDigits;
                            } catch (NumberFormatException ignored) {
                            }
                        }
```

**Review by gotson — COMMENTED** [review]
Thanks a lot for this PR

File: src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java (hunk 1 above)
Comment (sebasbaumh) [reply src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java:1073]: Your welcome :smile:

I would not use a regex as it is much slower than using a plain `indexOf` (which is just a small loop under the hood).
And the parsing calls would still be necessary.

Comment (gotson) [reply src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java:1073]: > I would not use a regex as it is much slower than using a plain `indexOf`

Is it? Even when the pattern is compiled only once?

Comment (sebasbaumh) [reply src/main/java/org/sqlite/jdbc3/JDBC3DatabaseMetaData.java:1073]: Yes, it is. There is no regex evaluation, which is much more expensive than just looping through a string by characters.
Though you could replace it, if you really like to and want more concise code.
I just wanted to add very performant code with a low memory overhead (small number of objects constructed on the heap). As I thought this might be called pretty often if multiple tables are queried or tables with a lot of columns.

I would use regex for more complex expressions, but here it is just to make sure two brackets are there and distinguishing between one and two parameters. Both variants still have to parse the value(s) to integers, so that part is the same.

**Comment by sebasbaumh** [comment]
Okay, I did a small benchmark. I just does not have any effect 😆

**Comment by sebasbaumh** [comment]
Parsing 3 columns 1000000 times did not make much difference, maybe it just gets optimized anyway.
So just go with the regex if you like.

**Comment by gotson** [comment]
I'm just maintaining the repo, it's not my code 🙃 

Will merge this as is, thanks!

**Comment by sebasbaumh** [comment]
Okay and thank you :smile:
